
'use server';

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceAnswerWithInternetSearchInputSchema = z.object({
  question: z.string().describe('The original user question or quiz question text.'),
  answer: z.string().describe('The initial answer or explanation generated by the AI based on the legal text.'),
  legalText: z.string().describe('The specific legal text/article identified as relevant to the question.'),
  keyConcept: z.string().optional().describe('A key legal concept derived from the question or answer, to guide searches.'),
});
export type EnhanceAnswerWithInternetSearchInput =
  z.infer<typeof EnhanceAnswerWithInternetSearchInputSchema>;

const EnhanceAnswerWithInternetSearchOutputSchema = z.object({
  enhancedAnswer: z.string().describe('The enhanced answer/explanation incorporating internet search results, legal reasoning, and precedents found. This should elaborate on the initial answer. For quiz questions, this might just be the original explanation if no further enhancement is applicable.'),
  searchLinks: z.array(z.string().url()).describe('An array of URLs to relevant jurisprudence, legal articles, or explanatory videos (e.g., YouTube).'),
  simulatedSourcedImageDescription: z.string().optional().describe("A textual description of an illustrative image one might find on a legal forum or contest preparation site related to the key concept or legal text. E.g., 'Diagram illustrating the stages of a criminal trial.'"),
  simulatedSourcedImageUrl: z.string().url().optional().describe("A placeholder URL for the described image (e.g., using placehold.co). This will be used as the primary image for the question."),
  simulatedSourcedMnemonic: z.string().optional().describe("A mnemonic or memory aid as if found on a specialized legal study site or forum, related to the key concept or legal text. E.g., 'Para lembrar os requisitos da legítima defesa: P.U.M.A. (Proporcionalidade, Utilização moderada dos meios, Moderação, Agressão injusta)'"),
});
export type EnhanceAnswerWithInternetSearchOutput =
  z.infer<typeof EnhanceAnswerWithInternetSearchOutputSchema>;

export async function enhanceAnswerWithInternetSearch(
  input: EnhanceAnswerWithInternetSearchInput
): Promise<EnhanceAnswerWithInternetSearchOutput> {
  return enhanceAnswerWithInternetSearchFlow(input);
}

const searchInternetTool = ai.defineTool(
  {
    name: 'searchInternetTool',
    description: 'Searches the internet for relevant legal information: jurisprudence, articles, explanatory videos (especially from YouTube), and common mnemonics or image concepts from study sites related to the provided legal question, answer, and text.',
    inputSchema: z.object({
      query: z.string().describe('A targeted search query based on the legal question, answer, and key concept. Should aim to find corroborating information, deeper insights, and examples of study aids.'),
      keyConcept: z.string().optional().describe('The key legal concept for focusing search on study aids like mnemonics and image descriptions, and video content.'),
    }),
    outputSchema: z.object({
        foundLinks: z.array(
            z.object({
                title: z.string().describe("Title of the search result."),
                link: z.string().url().describe("URL of the search result."),
                snippet: z.string().describe("A brief summary of the search result content."),
                type: z.enum(["jurisprudence", "article", "video", "forum_discussion", "youtube_video", "other"]).describe("Type of content. Use 'youtube_video' for YouTube links.")
            })
        ).describe('A list of relevant search results, including YouTube videos if found.'),
        exampleImageDescription: z.string().optional().describe("Example description of a relevant conceptual image found on a study site (e.g., 'Fluxograma do processo de inventário')."),
        exampleMnemonic: z.string().optional().describe("Example mnemonic found on a study site (e.g., 'Para as excludentes de ilicitude: LEET (Legítima Defesa, Estrito Cumprimento do Dever Legal, Exercício Regular de Direito, Estado de Necessidade)')."),
    }),
  },
  async (toolInput) => {
    // Placeholder implementation for internet search.
    console.log(`Simulating internet search for: ${toolInput.query} (Concept: ${toolInput.keyConcept})`);
    const imageDesc = toolInput.keyConcept ? `Ilustração conceitual sobre ${toolInput.keyConcept}, comum em materiais de estudo.` : undefined;
    const mnemonicText = toolInput.keyConcept ? `MACETE para ${toolInput.keyConcept}: Lembre-se de 'ABC' (Algo Bem Conceitual).` : undefined;
    
    const links = [
        {
            title: `Jurisprudência sobre: ${toolInput.query}`,
            link: `https://juris.example.com/search?q=${encodeURIComponent(toolInput.query)}`,
            snippet: `Análise jurisprudencial detalhada sobre ${toolInput.query}.`,
            type: "jurisprudence" as const
        },
        {
            title: `Artigo Explicativo: Entendendo ${toolInput.query}`,
            link: `https://legalblog.com/artigo/${encodeURIComponent(toolInput.query)}`,
            snippet: `Artigo de blog desmistificando ${toolInput.query}.`,
            type: "article" as const
        },
    ];

    if (toolInput.keyConcept) {
        links.push({
            title: `Vídeo Aula YouTube: ${toolInput.keyConcept}`,
            link: `https://youtube.com/results?search_query=${encodeURIComponent(toolInput.keyConcept + " direito")}`,
            snippet: `Vídeo aula no YouTube sobre ${toolInput.keyConcept}.`,
            type: "youtube_video" as const
        });
    }
    
    return {
        foundLinks: links,
        exampleImageDescription: imageDesc,
        exampleMnemonic: mnemonicText,
    };
  }
);

const prompt = ai.definePrompt({
  name: 'enhanceAnswerWithInternetSearchPrompt',
  tools: [searchInternetTool],
  input: {schema: EnhanceAnswerWithInternetSearchInputSchema},
  output: {schema: EnhanceAnswerWithInternetSearchOutputSchema},
  prompt: `Você é um assistente de pesquisa jurídica avançado.
  Dada uma pergunta (ou texto de questão de concurso), o texto legal relevante, uma resposta/explicação inicial e um conceito chave, sua tarefa é:
  1. Usar a ferramenta 'searchInternetTool' para encontrar informações adicionais na internet.
     Concentre a busca em:
     - Jurisprudência relevante.
     - Artigos legais ou de blogs que aprofundem o tema.
     - Links para vídeos explicativos, PRIORIZANDO vídeos do YouTube se disponíveis.
     - Com base no 'keyConcept', simule a busca por descrições de imagens ilustrativas e mnemônicos comuns em sites de estudo para concursos ou fóruns jurídicos.
  2. Analisar os resultados da busca.
  3. Formular uma 'enhancedAnswer' que integre as descobertas mais relevantes, se aplicável, ou mantenha a resposta inicial se for suficiente (especialmente para explicações de questões de concurso que já são baseadas na 'letra da lei').
  4. Compilar uma lista de 'searchLinks' com os URLs mais úteis (jurisprudência, artigos, vídeos do YouTube).
  5. Fornecer 'simulatedSourcedImageDescription': uma descrição textual de uma imagem ilustrativa relevante (como se encontrada em um site de estudos). Ex: "Fluxograma do recurso especial."
  6. Fornecer 'simulatedSourcedImageUrl': um URL de placeholder para esta imagem descrita (use https://placehold.co/600x400.png). ESTA SERÁ A IMAGEM PRINCIPAL USADA.
  7. Fornecer 'simulatedSourcedMnemonic': um mnemônico útil (como se encontrado em um fórum ou site especializado), com uma breve indicação de sua "origem" conceitual. Ex: "MACETE de cursinho para os requisitos da petição inicial: Endereçamento, Qualificação, Fatos, Direito, Pedido (EQFDP)."

  Contexto Fornecido:
  - Pergunta/Questão: {{{question}}}
  - Texto Legal Identificado: {{{legalText}}}
  - Resposta/Explicação Inicial: {{{answer}}}
  - Conceito Chave: {{{keyConcept}}}

  Instruções para o output (JSON):
  - 'enhancedAnswer': Mantenha ou elabore a resposta.
  - 'searchLinks': Array de URLs (incluir YouTube se pertinente).
  - 'simulatedSourcedImageDescription': Descrição da imagem simulada.
  - 'simulatedSourcedImageUrl': URL placeholder para a imagem (ex: https://placehold.co/600x400.png).
  - 'simulatedSourcedMnemonic': Mnemônico simulado.

  Seja preciso e referencie as fontes (tipos de fontes) conceitualmente ao descrever imagens e mnemônicos simulados.
  Priorize links do YouTube para vídeos, se encontrados.
  `,
});

const enhanceAnswerWithInternetSearchFlow = ai.defineFlow(
  {
    name: 'enhanceAnswerWithInternetSearchFlow',
    inputSchema: EnhanceAnswerWithInternetSearchInputSchema,
    outputSchema: EnhanceAnswerWithInternetSearchOutputSchema,
  },
  async (input) => {
    const {output, text: rawText} = await prompt(input);
     if (!output) {
      console.error(
        'enhanceAnswerWithInternetSearchFlow: LLM output failed to parse or was empty. Input:',
        input,
        'Raw LLM response text:',
        rawText
      );
      // Fallback to a simpler response if enhancement fails
      return {
        enhancedAnswer: input.answer, // Return initial answer
        searchLinks: [],
        simulatedSourcedImageDescription: "Nenhuma descrição de imagem adicional encontrada.",
        simulatedSourcedImageUrl: undefined, // No placeholder if no description
        simulatedSourcedMnemonic: "Nenhum mnemônico adicional encontrado."
      };
    }
    // Ensure placeholder URL if description exists but URL doesn't, or generate one if description is good but no URL
    if (output.simulatedSourcedImageDescription && !output.simulatedSourcedImageUrl) {
        // Generate a placeholder based on the description.
        const hint = output.simulatedSourcedImageDescription.toLowerCase().split(' ').slice(0,2).join(' ');
        output.simulatedSourcedImageUrl = `https://placehold.co/600x400.png`;
    } else if (!output.simulatedSourcedImageDescription && output.simulatedSourcedImageUrl) {
        // If somehow URL exists but no description, clear URL.
        output.simulatedSourcedImageUrl = undefined;
    }
    return output;
  }
);
