
'use server';

import {ai} from '@/ai/genkit';
import {z} from 'zod';
import type { IExternalLink } from '@/types'; // Import IExternalLink

const EnhanceAnswerWithInternetSearchInputSchema = z.object({
  question: z.string().describe('The original user question or quiz question text.'),
  answer: z.string().describe('The initial answer or explanation generated by the AI based on the legal text.'),
  legalText: z.string().describe('The specific legal text/article identified as relevant to the question.'),
  keyConcept: z.string().optional().describe('A key legal concept derived from the question or answer, to guide searches.'),
});
export type EnhanceAnswerWithInternetSearchInput =
  z.infer<typeof EnhanceAnswerWithInternetSearchInputSchema>;

const LinkObjectSchema = z.object({
    title: z.string().describe("Title of the search result."),
    link: z.string().url().describe("URL of the search result."),
    snippet: z.string().optional().describe("A brief summary of the search result content."),
    type: z.enum(["jurisprudence", "article", "video", "forum_discussion", "youtube_video", "instagram_video", "facebook_video", "other"]).describe("Type of content. Use specific video types for YouTube, Instagram, Facebook.")
});

const EnhanceAnswerWithInternetSearchOutputSchema = z.object({
  enhancedAnswer: z.string().describe('The enhanced answer/explanation incorporating internet search results, legal reasoning, and precedents found. This should elaborate on the initial answer. For quiz questions, this might just be the original explanation if no further enhancement is applicable.'),
  searchLinks: z.array(LinkObjectSchema).describe('An array of structured link objects to relevant jurisprudence, legal articles, or explanatory videos (YouTube, Instagram, Facebook).'),
  simulatedSourcedImageDescription: z.string().optional().describe("A textual description of an illustrative image one might find on a legal forum or contest preparation site related to the key concept or legal text. E.g., 'Diagram illustrating the stages of a criminal trial.' If no relevant image can be conceptualized, this should be explicitly stated (e.g., 'Nenhuma imagem conceitual relevante para este tema.') or left empty."),
  simulatedSourcedImageUrl: z.string().url().optional().describe("A placeholder URL for the described image (e.g., using placehold.co). Should only be provided if a relevant, positive image description exists. Leave empty if no relevant image description."),
  simulatedSourcedMnemonic: z.string().optional().describe("A mnemonic or memory aid as if found on a specialized legal study site or forum, related to the key concept or legal text. E.g., 'Para lembrar os requisitos da legítima defesa: P.U.M.A. (Proporcionalidade, Utilização moderada dos meios, Moderação, Agressão injusta)'"),
});
export type EnhanceAnswerWithInternetSearchOutput =
  z.infer<typeof EnhanceAnswerWithInternetSearchOutputSchema>;

export async function enhanceAnswerWithInternetSearch(
  input: EnhanceAnswerWithInternetSearchInput
): Promise<EnhanceAnswerWithInternetSearchOutput> {
  return enhanceAnswerWithInternetSearchFlow(input);
}

const searchInternetTool = ai.defineTool(
  {
    name: 'searchInternetTool',
    description: 'Searches the internet for relevant legal information: jurisprudence, articles, explanatory videos (especially from YouTube, Instagram, Facebook), and common mnemonics or image concepts from study sites related to the provided legal question, answer, and text.',
    inputSchema: z.object({
      query: z.string().describe('A targeted search query based on the legal question, answer, and key concept. Should aim to find corroborating information, deeper insights, and examples of study aids.'),
      keyConcept: z.string().optional().describe('The key legal concept for focusing search on study aids like mnemonics and image descriptions, and video content from YouTube, Instagram, and Facebook.'),
    }),
    outputSchema: z.object({
        foundLinks: z.array(LinkObjectSchema).describe('A list of relevant search results, including YouTube, Instagram, and Facebook videos if found. Ensure the "type" field is correctly set.'),
        exampleImageDescription: z.string().optional().describe("Example description of a relevant conceptual image found on a study site (e.g., 'Fluxograma do processo de inventário'). If no relevant image can be conceptualized, return an empty string or a phrase like 'Nenhuma imagem relevante.'"),
        exampleMnemonic: z.string().optional().describe("Example mnemonic found on a study site (e.g., 'Para as excludentes de ilicitude: LEET (Legítima Defesa, Estrito Cumprimento do Dever Legal, Exercício Regular de Direito, Estado de Necessidade)')."),
    }),
  },
  async (toolInput) => {
    // Placeholder implementation for internet search.
    console.log(`Simulating internet search for: ${toolInput.query} (Concept: ${toolInput.keyConcept})`);
    const imageDesc = toolInput.keyConcept ? `Ilustração conceitual sobre ${toolInput.keyConcept}, comum em materiais de estudo.` : `Nenhuma imagem conceitual relevante para ${toolInput.query}.`;
    const mnemonicText = toolInput.keyConcept ? `MACETE para ${toolInput.keyConcept}: Lembre-se de 'ABCDE' (Algo Bem Conceitual Detalhado Explicado).` : undefined;
    
    const links: IExternalLink[] = [
        {
            title: `Jurisprudência STF sobre: ${toolInput.query}`,
            link: `https://juris.stf.jus.br/search?q=${encodeURIComponent(toolInput.query)}`,
            snippet: `Decisões do STF relacionadas a ${toolInput.query}.`,
            type: "jurisprudence"
        },
        {
            title: `Artigo Explicativo Completo: Entendendo ${toolInput.query}`,
            link: `https://direitocomdesenho.com/artigo/${encodeURIComponent(toolInput.query.replace(/\s+/g, '-').toLowerCase())}`,
            snippet: `Artigo de blog aprofundado sobre ${toolInput.query}.`,
            type: "article"
        },
    ];

    if (toolInput.keyConcept) {
        links.push({
            title: `Vídeo Aula Essencial no YouTube: ${toolInput.keyConcept}`,
            link: `https://www.youtube.com/results?search_query=${encodeURIComponent(toolInput.keyConcept + " aula direito")}`,
            snippet: `Vídeo aula no YouTube sobre ${toolInput.keyConcept}.`,
            type: "youtube_video"
        });
        // Simulate finding (or not finding) Instagram/Facebook links
        if (Math.random() > 0.6) {
             links.push({
                title: `Dica Rápida no Instagram: ${toolInput.keyConcept}`,
                link: `https://www.instagram.com/explore/tags/${encodeURIComponent(toolInput.keyConcept.replace(/\s+/g, ''))}/`,
                snippet: `Posts e reels no Instagram sobre ${toolInput.keyConcept}.`,
                type: "instagram_video"
            });
        }
         if (Math.random() > 0.7) {
            links.push({
                title: `Discussão no Facebook: ${toolInput.keyConcept}`,
                link: `https://www.facebook.com/search/top/?q=${encodeURIComponent(toolInput.keyConcept + " direito")}`,
                snippet: `Grupos e posts no Facebook sobre ${toolInput.keyConcept}.`,
                type: "facebook_video" 
            });
        }
    }
    
    return {
        foundLinks: links,
        exampleImageDescription: imageDesc,
        exampleMnemonic: mnemonicText,
    };
  }
);

const prompt = ai.definePrompt({
  name: 'enhanceAnswerWithInternetSearchPrompt',
  tools: [searchInternetTool],
  input: {schema: EnhanceAnswerWithInternetSearchInputSchema},
  output: {schema: EnhanceAnswerWithInternetSearchOutputSchema},
  prompt: `Você é um assistente de pesquisa jurídica avançado.
  Dada uma pergunta (ou texto de questão de concurso), o texto legal relevante, uma resposta/explicação inicial e um conceito chave, sua tarefa é:
  1. Usar a ferramenta 'searchInternetTool' para encontrar informações adicionais na internet.
     Concentre a busca em:
     - Jurisprudência relevante.
     - Artigos legais ou de blogs que aprofundem o tema.
     - Links para vídeos explicativos, PRIORIZANDO vídeos do YouTube, Instagram e Facebook, se disponíveis. Certifique-se de que o campo 'type' no objeto de link retornado pela ferramenta seja 'youtube_video', 'instagram_video', ou 'facebook_video' para esses casos.
     - Com base no 'keyConcept', simule a busca por descrições de imagens ilustrativas e mnemônicos comuns em sites de estudo para concursos ou fóruns jurídicos.
  2. Analisar os resultados da busca.
  3. Formular uma 'enhancedAnswer' que integre as descobertas mais relevantes, se aplicável, ou mantenha a resposta inicial se for suficiente.
  4. Compilar uma lista de 'searchLinks' (objetos com title, link, snippet, type) com os URLs mais úteis (jurisprudência, artigos, vídeos do YouTube, Instagram, Facebook). Preserve o tipo de link fornecido pela ferramenta.
  5. Fornecer 'simulatedSourcedImageDescription': uma descrição textual de uma imagem ilustrativa RELEVANTE. Se nenhuma imagem conceitual relevante for aplicável, retorne uma string vazia ou 'Nenhuma imagem conceitual relevante para este tema.'
  6. Fornecer 'simulatedSourcedImageUrl': um URL de placeholder. Forneça APENAS SE uma 'simulatedSourcedImageDescription' relevante e positiva foi gerada. Caso contrário, string vazia ou nulo.
  7. Fornecer 'simulatedSourcedMnemonic': um mnemônico útil simulado.

  Contexto Fornecido:
  - Pergunta/Questão: {{{question}}}
  - Texto Legal Identificado: {{{legalText}}}
  - Resposta/Explicação Inicial: {{{answer}}}
  - Conceito Chave: {{{keyConcept}}}

  Instruções para o output (JSON):
  - 'searchLinks': Array de objetos {title, link, snippet, type}. Inclua vídeos do YouTube, Instagram, Facebook se pertinentes, com o 'type' correto.
  `,
});

const noImageResponseRegex = /nenhuma imagem|não encontrada|não aplicável/i;

const enhanceAnswerWithInternetSearchFlow = ai.defineFlow(
  {
    name: 'enhanceAnswerWithInternetSearchFlow',
    inputSchema: EnhanceAnswerWithInternetSearchInputSchema,
    outputSchema: EnhanceAnswerWithInternetSearchOutputSchema,
  },
  async (input) => {
    const {output, text: rawText} = await prompt(input);
     if (!output) {
      console.error(
        'enhanceAnswerWithInternetSearchFlow: LLM output failed to parse or was empty. Input:',
        input,
        'Raw LLM response text:',
        rawText
      );
      return {
        enhancedAnswer: input.answer, 
        searchLinks: [],
        simulatedSourcedImageDescription: "Nenhuma imagem conceitual relevante para este tema.",
        simulatedSourcedImageUrl: undefined, 
        simulatedSourcedMnemonic: "Nenhum mnemônico adicional encontrado."
      };
    }

    if (!output.searchLinks) { // Ensure searchLinks is at least an empty array
        output.searchLinks = [];
    }

    // Ensure URL is cleared if description is effectively absent or negative
    if (!output.simulatedSourcedImageDescription || output.simulatedSourcedImageDescription.trim() === "" || noImageResponseRegex.test(output.simulatedSourcedImageDescription)) {
        output.simulatedSourcedImageDescription = "Nenhuma imagem conceitual relevante para este tema."; // Standardize the "not found" text
        output.simulatedSourcedImageUrl = undefined;
    } else if (output.simulatedSourcedImageDescription && !output.simulatedSourcedImageUrl) {
        // If description is present and positive, but no URL, add placeholder
        output.simulatedSourcedImageUrl = `https://placehold.co/600x400.png`;
    } else if (!output.simulatedSourcedImageDescription && output.simulatedSourcedImageUrl) {
        // If somehow URL exists but no (valid) description, clear URL and set description.
        output.simulatedSourcedImageDescription = "Nenhuma imagem conceitual relevante para este tema.";
        output.simulatedSourcedImageUrl = undefined;
    }
    
    return output;
  }
);
