
'use server';

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceAnswerWithInternetSearchInputSchema = z.object({
  question: z.string().describe('The original user question.'),
  answer: z.string().describe('The initial answer generated by the AI based on the identified legal text.'),
  legalText: z.string().describe('The specific legal text/article identified as relevant to the question.'),
  keyConcept: z.string().optional().describe('A key legal concept derived from the question or answer.'),
});
export type EnhanceAnswerWithInternetSearchInput =
  z.infer<typeof EnhanceAnswerWithInternetSearchInputSchema>;

const EnhanceAnswerWithInternetSearchOutputSchema = z.object({
  enhancedAnswer: z.string().describe('The enhanced answer incorporating internet search results, legal reasoning, and precedents found. This should elaborate on the initial answer.'),
  searchLinks: z.array(z.string().url()).describe('An array of URLs to relevant jurisprudence, legal articles, or explanatory videos.'),
  simulatedSourcedImageDescription: z.string().optional().describe("A textual description of an illustrative image one might find on a legal forum or contest preparation site related to the key concept or legal text. E.g., 'Diagram illustrating the stages of a criminal trial.'"),
  simulatedSourcedImageUrl: z.string().url().optional().describe("A placeholder URL for the described image (e.g., using placehold.co)."),
  simulatedSourcedMnemonic: z.string().optional().describe("A mnemonic or memory aid as if found on a specialized legal study site or forum, related to the key concept or legal text. E.g., 'Para lembrar os requisitos da legítima defesa: P.U.M.A. (Proporcionalidade, Utilização moderada dos meios, Moderação, Agressão injusta)'"),
});
export type EnhanceAnswerWithInternetSearchOutput =
  z.infer<typeof EnhanceAnswerWithInternetSearchOutputSchema>;

export async function enhanceAnswerWithInternetSearch(
  input: EnhanceAnswerWithInternetSearchInput
): Promise<EnhanceAnswerWithInternetSearchOutput> {
  return enhanceAnswerWithInternetSearchFlow(input);
}

const searchInternetTool = ai.defineTool(
  {
    name: 'searchInternetTool',
    description: 'Searches the internet for relevant legal information: jurisprudence, articles, explanatory videos, and common mnemonics or image concepts from study sites related to the provided legal question, answer, and text.',
    inputSchema: z.object({
      query: z.string().describe('A targeted search query based on the legal question, answer, and key concept. Should aim to find corroborating information, deeper insights, and examples of study aids.'),
      keyConcept: z.string().optional().describe('The key legal concept for focusing search on study aids like mnemonics and image descriptions.'),
    }),
    outputSchema: z.object({
        foundLinks: z.array(
            z.object({
                title: z.string().describe("Title of the search result."),
                link: z.string().url().describe("URL of the search result."),
                snippet: z.string().describe("A brief summary of the search result content."),
                type: z.enum(["jurisprudence", "article", "video", "forum_discussion", "other"]).describe("Type of content.")
            })
        ).describe('A list of relevant search results.'),
        exampleImageDescription: z.string().optional().describe("Example description of a relevant conceptual image found on a study site."),
        exampleMnemonic: z.string().optional().describe("Example mnemonic found on a study site."),
    }),
  },
  async (toolInput) => {
    // Placeholder implementation for internet search.
    console.log(`Simulating internet search for: ${toolInput.query} (Concept: ${toolInput.keyConcept})`);
    const imageDesc = toolInput.keyConcept ? `Ilustração conceitual sobre ${toolInput.keyConcept}, comum em materiais de estudo.` : undefined;
    const mnemonicText = toolInput.keyConcept ? `MACETE para ${toolInput.keyConcept}: Lembre-se de 'ABC' (Algo Bem Conceitual).` : undefined;
    
    return {
        foundLinks: [
            {
                title: `Jurisprudência sobre: ${toolInput.query}`,
                link: `https://juris.example.com/search?q=${encodeURIComponent(toolInput.query)}`,
                snippet: `Análise jurisprudencial detalhada sobre ${toolInput.query}.`,
                type: "jurisprudence"
            },
            {
                title: `Artigo Explicativo: Entendendo ${toolInput.query}`,
                link: `https://legalblog.com/artigo/${encodeURIComponent(toolInput.query)}`,
                snippet: `Artigo de blog desmistificando ${toolInput.query}.`,
                type: "article"
            },
            {
                title: `Vídeo Aula: ${toolInput.keyConcept || toolInput.query}`,
                link: `https://youtube.com/results?search_query=${encodeURIComponent(toolInput.keyConcept || toolInput.query + " direito")}`,
                snippet: `Vídeo aula sobre ${toolInput.keyConcept || toolInput.query}.`,
                type: "video"
            }
        ],
        exampleImageDescription: imageDesc,
        exampleMnemonic: mnemonicText,
    };
  }
);

const prompt = ai.definePrompt({
  name: 'enhanceAnswerWithInternetSearchPrompt',
  tools: [searchInternetTool],
  input: {schema: EnhanceAnswerWithInternetSearchInputSchema},
  output: {schema: EnhanceAnswerWithInternetSearchOutputSchema},
  prompt: `Você é um assistente de pesquisa jurídica avançado.
  Dada uma pergunta do usuário, o texto legal relevante identificado, uma resposta inicial baseada nesse texto e um conceito chave, sua tarefa é:
  1. Usar a ferramenta 'searchInternetTool' para encontrar informações adicionais na internet que enriqueçam a resposta.
     Concentre a busca em:
     - Jurisprudência relevante.
     - Artigos legais ou de blogs que aprofundem o tema.
     - Links para vídeos explicativos (ex: YouTube).
     - Com base no 'keyConcept', simule a busca por descrições de imagens ilustrativas e mnemônicos comuns em sites de estudo para concursos ou fóruns jurídicos.
  2. Analisar os resultados da busca.
  3. Formular uma 'enhancedAnswer' que integre as descobertas mais relevantes, expandindo a resposta inicial. A resposta deve ser juridicamente sólida e, se possível, citar precedentes ou doutrinas encontradas.
  4. Compilar uma lista de 'searchLinks' com os URLs mais úteis (jurisprudência, artigos, vídeos).
  5. Fornecer 'simulatedSourcedImageDescription': uma descrição textual de uma imagem ilustrativa relevante (como se encontrada em um site de estudos).
  6. Fornecer 'simulatedSourcedImageUrl': um URL de placeholder para esta imagem descrita (use https://placehold.co/600x400.png).
  7. Fornecer 'simulatedSourcedMnemonic': um mnemônico útil (como se encontrado em um fórum ou site especializado), com uma breve indicação de sua "origem" conceitual.

  Contexto Fornecido:
  - Pergunta do Usuário: {{{question}}}
  - Texto Legal Identificado: {{{legalText}}}
  - Resposta Inicial (baseada no texto legal): {{{answer}}}
  - Conceito Chave: {{{keyConcept}}}

  Instruções para o output (JSON):
  - 'enhancedAnswer': Elabore a resposta enriquecida.
  - 'searchLinks': Array de URLs.
  - 'simulatedSourcedImageDescription': Descrição da imagem simulada.
  - 'simulatedSourcedImageUrl': URL placeholder para a imagem (ex: https://placehold.co/600x400.png).
  - 'simulatedSourcedMnemonic': Mnemônico simulado.

  Seja preciso e referencie as fontes (tipos de fontes) conceitualmente ao descrever imagens e mnemônicos simulados.
  Exemplo para mnemônico simulado: "MACETE de cursinho para lembrar os elementos X: L.I.M.P.E."
  Exemplo para descrição de imagem simulada: "Infográfico de um site jurídico explicando as etapas do recurso especial."
  `,
});

const enhanceAnswerWithInternetSearchFlow = ai.defineFlow(
  {
    name: 'enhanceAnswerWithInternetSearchFlow',
    inputSchema: EnhanceAnswerWithInternetSearchInputSchema,
    outputSchema: EnhanceAnswerWithInternetSearchOutputSchema,
  },
  async (input) => {
    const {output, text: rawText} = await prompt(input);
     if (!output) {
      console.error(
        'enhanceAnswerWithInternetSearchFlow: LLM output failed to parse or was empty. Input:',
        input,
        'Raw LLM response text:',
        rawText
      );
      // Fallback to a simpler response if enhancement fails
      return {
        enhancedAnswer: input.answer, // Return initial answer
        searchLinks: [],
        simulatedSourcedImageDescription: "Nenhuma descrição de imagem adicional encontrada.",
        simulatedSourcedImageUrl: undefined,
        simulatedSourcedMnemonic: "Nenhum mnemônico adicional encontrado."
      };
    }
    // Ensure placeholder URL if description exists but URL doesn't
    if (output.simulatedSourcedImageDescription && !output.simulatedSourcedImageUrl) {
        output.simulatedSourcedImageUrl = `https://placehold.co/600x400.png?text=${encodeURIComponent(output.simulatedSourcedImageDescription.substring(0,30))}`;
    }
    return output;
  }
);
