
'use server';

/**
 * @fileOverview Generates multiple-choice or true/false questions from legal text,
 * then enriches each question with mnemonics, search links, and a conceptual image.
 *
 * - generateQuestions - Main function to generate and enrich questions.
 * - GenerateQuestionsInput - Input: legal text, number of questions, style.
 * - GenerateQuestionsOutput - Output: array of enriched IQGeneratedQuestion objects.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import type { QuestionStyle, IQGeneratedQuestion } from '@/types';
import { generateMnemonics, type GenerateMnemonicsInput } from './generate-mnemonics';
import { enhanceAnswerWithInternetSearch, type EnhanceAnswerWithInternetSearchInput } from './enhance-answer-with-internet-search'; // Assuming this output has searchLinks
import { generateImageForQuestion, type GenerateImageForQuestionInput } from './generate-image-for-question';

const GenerateQuestionsInputSchema = z.object({
  legalText: z.string().describe('The legal text to generate questions from.'),
  numQuestions: z.number().int().min(1).max(10).describe('The number of questions to generate (1-10).'),
  questionStyle: z.enum(['cespe', 'mcq4', 'mcq5']).describe('The style of the questions: "cespe" (True/False), "mcq4" (4 multiple choice options), "mcq5" (5 multiple choice options).'),
});
export type GenerateQuestionsInput = z.infer<typeof GenerateQuestionsInputSchema>;

// Schema for a single question generated by the initial prompt (before enrichment)
const BaseQuestionObjectSchema = z.object({
    question: z.string().describe('The question text or affirmative statement for Cespe style.'),
    options: z.array(z.string()).describe('Answer options. For "cespe", this will be ["Certo", "Errado"]. For "mcq4", 4 options. For "mcq5", 5 options. Options should contain only the text, without prefixes like "A)", "B)".'),
    correctAnswerIndex: z.number().int().min(0).describe('Index of the correct answer in the options array (0-1 for Cespe, 0-3 for mcq4, 0-4 for mcq5).'),
    explanation: z.string().describe('Explanation of why the answer is correct, referencing the legal text strictly (letra da lei).'),
    keyConceptForEnrichment: z.string().optional().describe('A 2-5 word key concept from the question/explanation, to guide mnemonic and image generation.'),
}).refine(
    (data) => {
      // Validation for options based on questionStyle is implicitly handled by the prompt now.
      // Explicit validation for options content for Cespe:
      if (data.options.length === 2 && !(data.options.map(o => o.toLowerCase()).includes("certo") && data.options.map(o => o.toLowerCase()).includes("errado")) ) {
        //This refinement is tricky if the prompt itself defines the style. We'll rely on prompt for style compliance.
      }
      return true; 
    }
);


// Schema for the output of the main question generation prompt
const BaseGenerateQuestionsOutputSchema = z.object({
  questions: z.array(BaseQuestionObjectSchema).describe('An array of question objects, matching the requested style and count.'),
});


// Final output schema for the entire flow, including enrichments
const EnrichedQuestionObjectSchema = BaseQuestionObjectSchema.extend({
  questionStyle: z.enum(['cespe', 'mcq4', 'mcq5']), // Added to each question object
  aiGeneratedMnemonics: z.array(z.string()).optional(),
  externalSearchLinks: z.array(z.string().url()).optional(),
  aiGeneratedImageDataUri: z.string().url().nullable().optional(),
});

const GenerateQuestionsOutputSchema = z.object({
  questions: z.array(EnrichedQuestionObjectSchema),
});
export type GenerateQuestionsOutput = z.infer<typeof GenerateQuestionsOutputSchema>;


export async function generateQuestions(input: GenerateQuestionsInput): Promise<GenerateQuestionsOutput> {
  return generateQuestionsFlow(input);
}

// Prompt to generate the base questions
const generateBaseQuestionsPrompt = ai.definePrompt({
  name: 'generateBaseQuestionsPrompt',
  input: {schema: GenerateQuestionsInputSchema},
  output: {schema: BaseGenerateQuestionsOutputSchema},
  prompt: `Você é um especialista em criar questões de concurso a partir de textos legais, no estilo especificado.
Gere {{numQuestions}} questão(ões) a partir do texto legal fornecido, aderindo estritamente ao estilo '{{questionStyle}}'.
A resposta DEVE ser um objeto JSON com uma chave "questions", contendo um array de objetos de questão.

Instruções para cada estilo de questão:
1.  Se 'questionStyle' for 'cespe':
    *   'question': Elabore uma afirmativa sobre o texto legal.
    *   'options': Deve ser um array com duas strings: ["Certo", "Errado"] (ou ["Errado", "Certo"], a ordem não importa, mas o correctAnswerIndex deve corresponder).
    *   'correctAnswerIndex': 0 se "Certo" for a resposta correta na primeira posição, 1 se "Errado" (ou vice-versa).
    *   'explanation': Explicação concisa baseada na "letra da lei", justificando a resposta.
    *   'keyConceptForEnrichment': Um conceito chave de 2-5 palavras da questão/lei para guiar a geração de mnemônicos e imagens.
2.  Se 'questionStyle' for 'mcq4':
    *   'question': Elabore uma pergunta sobre o texto legal.
    *   'options': Array com 4 strings, sendo uma correta e três distratores plausíveis. NÃO inclua prefixos como "A)", "B)".
    *   'correctAnswerIndex': Índice (0-3) da opção correta.
    *   'explanation': Explicação baseada na "letra da lei".
    *   'keyConceptForEnrichment': Um conceito chave de 2-5 palavras.
3.  Se 'questionStyle' for 'mcq5':
    *   'question': Elabore uma pergunta sobre o texto legal.
    *   'options': Array com 5 strings, uma correta e quatro distratores. NÃO inclua prefixos como "A)", "B)".
    *   'correctAnswerIndex': Índice (0-4) da opção correta.
    *   'explanation': Explicação baseada na "letra da lei".
    *   'keyConceptForEnrichment': Um conceito chave de 2-5 palavras.

Certifique-se que o JSON de saída é válido e que cada objeto de questão no array "questions" contém todas as chaves solicitadas.
A explicação deve ser estritamente baseada no texto legal fornecido.

Texto Legal:
\`\`\`
{{{legalText}}}
\`\`\`
`,
});

// Main flow
const generateQuestionsFlow = ai.defineFlow(
  {
    name: 'generateQuestionsFlow',
    inputSchema: GenerateQuestionsInputSchema,
    outputSchema: GenerateQuestionsOutputSchema,
  },
  async (input) => {
    // 1. Generate base questions
    const baseQuestionsResult = await generateBaseQuestionsPrompt(input);
    if (!baseQuestionsResult.output || !baseQuestionsResult.output.questions || baseQuestionsResult.output.questions.length === 0) {
      console.error(
        'generateQuestionsFlow: Failed to generate base questions. Input:', input, 'Raw LLM response:', baseQuestionsResult.text
      );
      throw new Error('A IA falhou ao gerar as questões base no formato esperado.');
    }

    const baseQuestions = baseQuestionsResult.output.questions;
    const enrichedQuestions: IQGeneratedQuestion[] = [];

    // 2. Enrich each question
    for (const baseQuestion of baseQuestions) {
      if (!baseQuestion.question || !baseQuestion.options || baseQuestion.correctAnswerIndex === undefined || !baseQuestion.explanation) {
        console.warn('Skipping enrichment for malformed base question:', baseQuestion);
        // Add the base question with the required style, but without enrichments if it's malformed
        enrichedQuestions.push({
            ...baseQuestion,
            question: baseQuestion.question || "Erro na questão",
            options: baseQuestion.options || ["Erro", "Erro"],
            correctAnswerIndex: baseQuestion.correctAnswerIndex === undefined ? 0 : baseQuestion.correctAnswerIndex,
            explanation: baseQuestion.explanation || "Erro na explicação",
            questionStyle: input.questionStyle, // Assign the overall style
        });
        continue;
      }
      
      const keyConcept = baseQuestion.keyConceptForEnrichment || baseQuestion.question.substring(0,50); // Fallback for keyConcept

      try {
        const mnemonicInput: GenerateMnemonicsInput = {
          legalText: input.legalText, // Provide full legal text for broader context for mnemonics
          question: baseQuestion.question,
          answer: baseQuestion.explanation,
        };
        const searchInput: EnhanceAnswerWithInternetSearchInput = {
          question: baseQuestion.question,
          answer: baseQuestion.explanation, // AI's explanation for the question
          legalText: input.legalText, // Specific snippet or full text
          keyConcept: keyConcept,
        };
        const imageInput: GenerateImageForQuestionInput = {
          question: baseQuestion.question,
          correctAnswerText: baseQuestion.explanation,
          legalConcept: keyConcept,
        };

        // Run enrichments in parallel
        const [mnemonicsResult, searchResult, imageResult] = await Promise.allSettled([
          generateMnemonics(mnemonicInput),
          enhanceAnswerWithInternetSearch(searchInput),
          generateImageForQuestion(imageInput),
        ]);

        const aiGeneratedMnemonics = mnemonicsResult.status === 'fulfilled' ? mnemonicsResult.value.mnemonics : [];
        const externalSearchLinks = searchResult.status === 'fulfilled' ? searchResult.value.searchLinks : [];
        const aiGeneratedImageDataUri = imageResult.status === 'fulfilled' ? imageResult.value.imageDataUri : null;

        enrichedQuestions.push({
          ...baseQuestion,
          questionStyle: input.questionStyle, // Add questionStyle to each question
          aiGeneratedMnemonics,
          externalSearchLinks,
          aiGeneratedImageDataUri,
        });

      } catch (enrichmentError) {
        console.error('Error during question enrichment:', enrichmentError, 'Base question:', baseQuestion);
        // Add question with available data even if enrichment fails for one part
         enrichedQuestions.push({
          ...baseQuestion,
          questionStyle: input.questionStyle,
        });
      }
    }
    
    if (enrichedQuestions.length !== input.numQuestions) {
        console.warn(`generateQuestionsFlow: Expected ${input.numQuestions} questions, but generated/enriched ${enrichedQuestions.length}.`);
        // Potentially throw error or handle as partial success depending on requirements
    }


    return { questions: enrichedQuestions };
  }
);
