
'use server';

/**
 * @fileOverview Generates multiple-choice or true/false questions from legal text,
 * then enriches each question with mnemonics, search links, and a conceptual image.
 * Can also incorporate simulated external questions.
 *
 * - generateQuestions - Main function to generate and enrich questions.
 * - GenerateQuestionsInput - Input: legal text, num questions, style, option to fetch external.
 * - GenerateQuestionsOutput - Output: array of enriched IQGeneratedQuestion objects.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';
import type { IQGeneratedQuestion } from '@/types'; // IQGeneratedQuestion now includes 'source'
import { generateMnemonics, type GenerateMnemonicsInput } from './generate-mnemonics';
import { enhanceAnswerWithInternetSearch, type EnhanceAnswerWithInternetSearchInput, type EnhanceAnswerWithInternetSearchOutput } from './enhance-answer-with-internet-search';
import { findSimulatedExternalQuestions, type FindSimulatedExternalQuestionsInput, type FindSimulatedExternalQuestionsOutput } from './find-simulated-external-questions';

const GenerateQuestionsInputSchema = z.object({
  legalText: z.string().describe('The legal text to generate questions from.'),
  numQuestions: z.number().int().min(1).max(10).describe('The number of INÉDITA DANTASAI questions to generate (1-10).'),
  questionStyle: z.enum(['cespe', 'mcq4', 'mcq5']).describe('The style of the questions: "cespe" (True/False), "mcq4" (4 multiple choice options), "mcq5" (5 multiple choice options).'),
  subject: z.string().optional().describe('The subject/matéria of the legal text.'),
  topic: z.string().optional().describe('The specific topic within the subject.'),
  fetchSimulatedExternal: z.boolean().optional().default(false).describe('Whether to include simulated questions from exam boards.'),
  numSimulatedExternal: z.number().int().min(1).max(3).optional().default(2).describe('Number of simulated external questions to try to fetch (1-3).')
});
export type GenerateQuestionsInput = z.infer<typeof GenerateQuestionsInputSchema>;

// Schema for a single question generated by the initial prompt (before enrichment)
// This is for "INÉDITA DANTASAI" questions.
const BaseQuestionObjectSchema = z.object({
    question: z.string().describe('The question text or affirmative statement for Cespe style.'),
    options: z.array(z.string()).describe('Answer options. For "cespe", this will be ["Certo", "Errado"]. For "mcq4", 4 options. For "mcq5", 5 options. Options should contain only the text, without prefixes like "A)", "B)".'),
    correctAnswerIndex: z.number().int().min(0).describe('Index of the correct answer in the options array (0-1 for Cespe, 0-3 for mcq4, 0-4 for mcq5).'),
    explanation: z.string().describe('Explanation of why the answer is correct, referencing the legal text strictly (letra da lei).'),
    keyConceptForEnrichment: z.string().optional().describe('A 2-5 word key concept from the question/explanation, to guide mnemonic and image generation.'),
    // Source will be added explicitly after generation
}).refine(
    (data) => {
      // This refinement is based on the *implicit* style from options length,
      // which should align with the requested questionStyle for INÉDITA questions.
      if (data.options.length === 2) { // Cespe
         return data.correctAnswerIndex === 0 || data.correctAnswerIndex === 1;
      }
      if (data.options.length === 4) { // MCQ4
        return data.correctAnswerIndex >= 0 && data.correctAnswerIndex < 4;
      }
      if (data.options.length === 5) { // MCQ5
        return data.correctAnswerIndex >= 0 && data.correctAnswerIndex < 5;
      }
      return true; // Allow pass-through if options length doesn't match known styles (should be caught by main style check)
    },
    { message: "Base question options and correctAnswerIndex do not match the implicit question style based on options length."}
);


// Schema for the output of the main question generation prompt for INÉDITA questions
const BaseGenerateQuestionsOutputSchema = z.object({
  questions: z.array(BaseQuestionObjectSchema).describe('An array of question objects, matching the requested style and count.'),
});


// Schema for a fully enriched question, matching IQGeneratedQuestion type
const EnrichedQuestionSchema = z.object({
  question: z.string(),
  options: z.array(z.string()),
  correctAnswerIndex: z.number().int().min(0),
  explanation: z.string(),
  keyConceptForEnrichment: z.string().optional(),
  id: z.string(), 
  questionStyle: z.enum(['cespe', 'mcq4', 'mcq5']),
  source: z.string(), // Now mandatory, e.g., "INÉDITA DANTASAI" or "Simulado: Cespe..."
  subject: z.string().optional(),
  topic: z.string().optional(),
  aiGeneratedMnemonics: z.array(z.string()).optional(),
  externalSearchLinks: z.array(z.string().url()).optional(),
  simulatedSourcedImageDescription: z.string().optional(),
  simulatedSourcedImageUrl: z.string().url().optional(),
  simulatedSourcedMnemonic: z.string().optional(),
}).refine(
  (data) => {
    switch (data.questionStyle) {
      case 'cespe':
        return data.options.length === 2 && data.correctAnswerIndex >= 0 && data.correctAnswerIndex < 2;
      case 'mcq4':
        return data.options.length === 4 && data.correctAnswerIndex >= 0 && data.correctAnswerIndex < 4;
      case 'mcq5':
        return data.options.length === 5 && data.correctAnswerIndex >= 0 && data.correctAnswerIndex < 5;
      default:
        return false; 
    }
  },
  { message: "Enriched question's options length or correctAnswerIndex does not match the specified questionStyle." }
);

const GenerateQuestionsOutputSchema = z.object({
  questions: z.array(EnrichedQuestionSchema).describe('An array of fully enriched question objects, potentially mixed sources.'),
});
export type GenerateQuestionsOutput = z.infer<typeof GenerateQuestionsOutputSchema>;


export async function generateQuestions(input: GenerateQuestionsInput): Promise<GenerateQuestionsOutput> {
  return generateQuestionsFlow(input);
}

// Prompt to generate the base "INÉDITA DANTASAI" questions
const generateBaseQuestionsPrompt = ai.definePrompt({
  name: 'generateIneditaDantasaiQuestionsPrompt',
  input: {schema: GenerateQuestionsInputSchema}, // Uses the main input to know style, numQuestions, etc.
  output: {schema: BaseGenerateQuestionsOutputSchema},
  prompt: `Você é um especialista em criar questões de concurso INÉDITAS (estilo "INÉDITA DANTASAI") a partir de textos legais, no estilo especificado.
Gere {{numQuestions}} questão(ões) INÉDITAS a partir do texto legal fornecido, aderindo estritamente ao estilo '{{questionStyle}}'.
A resposta DEVE ser um objeto JSON com uma chave "questions", contendo um array de objetos de questão INÉDITA.

Instruções para cada estilo de questão:
1.  Se 'questionStyle' for 'cespe':
    *   'question': Elabore uma afirmativa sobre o texto legal.
    *   'options': Deve ser um array com duas strings: ["Certo", "Errado"].
    *   'correctAnswerIndex': 0 se "Certo" for a correta, 1 se "Errado" for. (Ou vice-versa se a ordem das options for invertida).
    *   'explanation': Explicação concisa baseada na "letra da lei", justificando a resposta.
    *   'keyConceptForEnrichment': Um conceito chave de 2-5 palavras.
2.  Se 'questionStyle' for 'mcq4':
    *   'question': Elabore uma pergunta sobre o texto legal.
    *   'options': Array com 4 strings (uma correta, três distratores). NÃO inclua prefixos como "A)".
    *   'correctAnswerIndex': Índice (0-3) da opção correta.
    *   'explanation': Explicação baseada na "letra da lei".
    *   'keyConceptForEnrichment': Um conceito chave de 2-5 palavras.
3.  Se 'questionStyle' for 'mcq5':
    *   'question': Elabore uma pergunta sobre o texto legal.
    *   'options': Array com 5 strings (uma correta, quatro distratores). NÃO inclua prefixos como "A)".
    *   'correctAnswerIndex': Índice (0-4) da opção correta.
    *   'explanation': Explicação baseada na "letra da lei".
    *   'keyConceptForEnrichment': Um conceito chave de 2-5 palavras.

Certifique-se que o JSON de saída é válido. A explicação deve ser estritamente baseada no texto legal fornecido.

Texto Legal:
\`\`\`
{{{legalText}}}
\`\`\`
`,
});

// Main flow
const generateQuestionsFlow = ai.defineFlow(
  {
    name: 'generateQuestionsFlow',
    inputSchema: GenerateQuestionsInputSchema,
    outputSchema: GenerateQuestionsOutputSchema,
  },
  async (input) => {
    let allBaseQuestions: (z.infer<typeof BaseQuestionObjectSchema> & { source: string, questionStyle: GenerateQuestionsInput['questionStyle'] })[] = [];

    // 1. Generate INÉDITA DANTASAI questions
    const ineditaResult = await generateBaseQuestionsPrompt(input);
    if (ineditaResult.output && ineditaResult.output.questions) {
      allBaseQuestions.push(
        ...ineditaResult.output.questions.map(q => ({ 
            ...q, 
            source: "INÉDITA DANTASAI",
            questionStyle: input.questionStyle // Ensure style is set from input
        }))
      );
    } else {
      console.warn('generateQuestionsFlow: Failed to generate INÉDITA DANTASAI questions. Raw LLM response:', ineditaResult.text);
    }

    // 2. Fetch/Generate SIMULATED EXTERNAL questions if requested
    if (input.fetchSimulatedExternal) {
      const externalInput: FindSimulatedExternalQuestionsInput = {
        legalText: input.legalText,
        subject: input.subject,
        topic: input.topic,
        numQuestions: input.numSimulatedExternal || 2,
        targetQuestionStyle: input.questionStyle, // Generate simulated in the same style for consistency for now
      };
      try {
        const externalResult = await findSimulatedExternalQuestions(externalInput);
        if (externalResult.questions) {
          allBaseQuestions.push(...externalResult.questions.map(q => ({...q, questionStyle: q.questionStyle || input.questionStyle }))); // source is already in externalResult.questions
        }
      } catch (e) {
         console.error('generateQuestionsFlow: Error fetching/generating simulated external questions:', e);
      }
    }
    
    if (allBaseQuestions.length === 0) {
       console.error(
        'generateQuestionsFlow: No base questions generated (neither INÉDITA nor simulated). Input:', input
      );
      throw new Error('A IA falhou ao gerar as questões base. Verifique o console do servidor para mais detalhes.');
    }

    const enrichedQuestions: IQGeneratedQuestion[] = []; 

    // 3. Enrich ALL questions (both INÉDITA and SIMULATED EXTERNAL)
    for (const baseQuestion of allBaseQuestions) {
      if (!baseQuestion.question || !baseQuestion.options || baseQuestion.correctAnswerIndex === undefined || !baseQuestion.explanation) {
        console.warn('Skipping enrichment for malformed base question:', baseQuestion);
        enrichedQuestions.push({
            ...baseQuestion,
            id: `${Date.now()}-malformed-${Math.random().toString(16).slice(2)}`, 
            question: baseQuestion.question || "Erro: Questão não gerada corretamente",
            options: baseQuestion.options || ["Erro", "Erro"],
            correctAnswerIndex: baseQuestion.correctAnswerIndex === undefined ? 0 : baseQuestion.correctAnswerIndex,
            explanation: baseQuestion.explanation || "Erro: Explicação não gerada",
            questionStyle: baseQuestion.questionStyle || input.questionStyle,
            source: baseQuestion.source || "Erro: Fonte Desconhecida",
            subject: input.subject,
            topic: input.topic,
        });
        continue;
      }
      
      const keyConcept = baseQuestion.keyConceptForEnrichment || baseQuestion.question.substring(0,50); 

      try {
        const mnemonicInput: GenerateMnemonicsInput = {
          legalText: input.legalText, 
          question: baseQuestion.question,
          answer: baseQuestion.explanation, 
        };
        const searchInput: EnhanceAnswerWithInternetSearchInput = {
          question: baseQuestion.question,
          answer: baseQuestion.explanation, 
          legalText: input.legalText, 
          keyConcept: keyConcept,
        };

        // Promise.allSettled to ensure all enrichments are attempted even if one fails
        const [mnemonicsResult, searchResult] = await Promise.allSettled([
          generateMnemonics(mnemonicInput),
          enhanceAnswerWithInternetSearch(searchInput),
        ]);

        const aiGeneratedMnemonics = mnemonicsResult.status === 'fulfilled' ? mnemonicsResult.value.mnemonics : [];
        
        let searchData: Partial<EnhanceAnswerWithInternetSearchOutput> = {};
        if (searchResult.status === 'fulfilled' && searchResult.value) {
            searchData = {
                externalSearchLinks: searchResult.value.searchLinks,
                simulatedSourcedImageDescription: searchResult.value.simulatedSourcedImageDescription,
                simulatedSourcedImageUrl: searchResult.value.simulatedSourcedImageUrl,
                simulatedSourcedMnemonic: searchResult.value.simulatedSourcedMnemonic,
            };
        }
        
        enrichedQuestions.push({
          ...baseQuestion,
          id: `${Date.now()}-q-${enrichedQuestions.length}`,
          questionStyle: baseQuestion.questionStyle, // This should be set correctly from baseQuestion
          source: baseQuestion.source, // This should be set correctly from baseQuestion
          subject: input.subject,
          topic: input.topic,
          aiGeneratedMnemonics,
          externalSearchLinks: searchData.externalSearchLinks,
          simulatedSourcedImageDescription: searchData.simulatedSourcedImageDescription,
          simulatedSourcedImageUrl: searchData.simulatedSourcedImageUrl,
          simulatedSourcedMnemonic: searchData.simulatedSourcedMnemonic,
        });

      } catch (enrichmentError) {
        console.error('Error during question enrichment:', enrichmentError, 'Base question:', baseQuestion);
         enrichedQuestions.push({
          ...baseQuestion,
          id: `${Date.now()}-enricherror-${enrichedQuestions.length}`,
          questionStyle: baseQuestion.questionStyle,
          source: baseQuestion.source,
          subject: input.subject,
          topic: input.topic,
        });
      }
    }
    
    const totalExpectedQuestions = input.numQuestions + (input.fetchSimulatedExternal ? (input.numSimulatedExternal || 0) : 0);
    if (enrichedQuestions.length === 0 && allBaseQuestions.length > 0) {
         console.warn(`generateQuestionsFlow: All base questions failed enrichment. Base count: ${allBaseQuestions.length}`);
    } else if (enrichedQuestions.length < allBaseQuestions.length) {
         console.warn(`generateQuestionsFlow: Some questions failed enrichment. Base count: ${allBaseQuestions.length}, Enriched count: ${enrichedQuestions.length}`);
    } else if (allBaseQuestions.length === 0) {
         console.warn(`generateQuestionsFlow: No questions were generated at all (neither INÉDITA nor simulated).`);
    }


    return { questions: enrichedQuestions };
  }
);
