
export type QuestionStyle = 'cespe' | 'mcq4' | 'mcq5'; // Kept for now, but not used in the new flow

// Represents the AI's generated answer to a user's legal question
export interface ILegalAnswer {
  id: string; // Unique ID for this answer event
  userQuestion: string; // The user's original question
  explanation: string; // Detailed explanation generated by the AI
  citedArticle: string; // The specific legal article/text identified by the AI
  
  // AI-generated content
  aiGeneratedImageDataUri?: string | null; // Image generated by AI (e.g., conceptual)
  aiGeneratedMnemonics?: string[]; // Mnemonics generated by AI based on the cited article

  // "Sourced" content (simulated by AI)
  enhancedExplanation?: string; // Explanation potentially expanded with "internet findings"
  externalSearchLinks?: string[]; // Links to external resources (jurisprudence, blogs, videos)
  sourcedImageDescription?: string; // Description of an ideal image from a specialized source
  sourcedImageUrl?: string; // Placeholder URL for the described "sourced" image
  sourcedMnemonic?: string; // A mnemonic as if found on a specialized site/forum
  
  timestamp: number;
}


// --- Old types (might be deprecated or removed if quiz functionality is fully gone) ---
export interface IQGeneratedQuestion {
  question: string;
  options: string[];
  correctAnswerIndex: number;
  explanation: string;
  questionStyle: QuestionStyle;
  mnemonic?: string;
  searchLinks?: string[];
}

export interface IAnsweredQuestion extends IQGeneratedQuestion {
  id: string;
  legalTextContext: string;
  userAnswerIndex: number;
  isCorrect: boolean;
  enhancedExplanation?: string;
  additionalSearchLinks?: string[];
  generatedMnemonics?: string[];
  imageDataUri?: string | null;
  timestamp: number;
}
// Ensure ILegalAnswer is used for history if the functionality changes significantly
// For now, history page uses IAnsweredQuestion, which might need an update or a new history type
