
export type QuestionStyle = 'cespe' | 'mcq4' | 'mcq5';

// Represents a question generated by the AI, before being answered by the user
// This is the primary structure for questions generated by the generateQuestions flow
export interface IQGeneratedQuestion {
  question: string;
  options: string[]; // For "cespe", ["Certo", "Errado"]. For "mcq", the actual options.
  correctAnswerIndex: number;
  explanation: string; // Explanation based on "letra da lei"
  questionStyle: QuestionStyle;
  
  // Enriched content for each question
  aiGeneratedMnemonics?: string[];
  externalSearchLinks?: string[]; // Links from simulated internet search
  aiGeneratedImageDataUri?: string | null; // Image generated by AI for this specific question
}

// Represents a question after the user has answered it, including their answer and correctness
export interface IAnsweredQuestion extends IQGeneratedQuestion {
  id: string; // Unique ID for this answered question instance
  legalTextContext: string; // The original legal text provided by the user
  userAnswerIndex: number | null; // User's selected answer index, null if skipped or not answered
  isCorrect: boolean | null; // True if user's answer is correct, null if not answered/applicable
  timestamp: number;
}

// This type was for the "legal assistant" functionality and is now secondary or deprecated
export interface ILegalAnswer {
  id: string;
  userQuestion: string;
  explanation: string;
  citedArticle: string;
  aiGeneratedImageDataUri?: string | null;
  aiGeneratedMnemonics?: string[];
  enhancedExplanation?: string;
  externalSearchLinks?: string[];
  sourcedImageDescription?: string;
  sourcedImageUrl?: string;
  sourcedMnemonic?: string;
  timestamp: number;
}
