
export type QuestionStyle = 'cespe' | 'mcq4' | 'mcq5';

export interface IExternalLink {
  title: string;
  link: string;
  snippet?: string;
  type: 'jurisprudence' | 'article' | 'video' | 'forum_discussion' | 'youtube_video' | 'instagram_video' | 'facebook_video' | 'other';
}

// Represents a question generated by the AI, before being answered by the user
// This is the primary structure for questions generated by the generateQuestions flow
export interface IQGeneratedQuestion {
  id: string; // Unique ID for this question generation instance (can be re-used for IAnsweredQuestion)
  question: string;
  options: string[]; // For "cespe", ["Certo", "Errado"]. For "mcq", the actual options.
  correctAnswerIndex: number;
  explanation: string; // Explanation based on "letra da lei"
  questionStyle: QuestionStyle;
  keyConceptForEnrichment?: string; // Used internally by generateQuestions flow

  // User-defined context
  subject?: string; // Matéria
  topic?: string; // Tópico

  // Source of the question
  source: string; // e.g., "INÉDITA DANTASAI" or "Semelhante: Cespe - 2023 - Analista"

  // Enriched content for each question
  aiGeneratedMnemonics?: string[];
  externalSearchLinks?: IExternalLink[]; // Links from simulated internet search
  // Simulated sourced content (from enhanceAnswerWithInternetSearch)
  simulatedSourcedImageDescription?: string;
  simulatedSourcedImageUrl?: string;
  simulatedSourcedMnemonic?: string;
}

// Represents a question after the user has answered it, including their answer and correctness
export interface IAnsweredQuestion extends IQGeneratedQuestion {
  legalTextContext: string; // The original legal text provided by the user for generating this set of questions
  userAnswerIndex: number | null; // User's selected answer index, null if skipped or not answered
  isCorrect: boolean | null; // True if user's answer is correct, null if not answered/applicable
  timestamp: number;
}

// This type was for the "legal assistant" functionality (now secondary/removed from main page)
export interface ILegalAnswer {
  id: string;
  userQuestion: string;
  explanation: string;
  citedArticle: string;
  // aiGeneratedImageDataUri?: string | null;  // This was removed as per user request for question generation
  aiGeneratedMnemonics?: string[];
  enhancedExplanation?: string;
  externalSearchLinks?: IExternalLink[]; // Updated to use IExternalLink
  sourcedImageDescription?: string;
  sourcedImageUrl?: string;
  sourcedMnemonic?: string;
  timestamp: number;
}

// For performance page
export interface SubjectPerformance {
  subject: string;
  correct: number;
  incorrect: number;
  total: number;
  percentage: number;
}
